# OpenBioCure-Ingestion Configuration

app:
  name: "OpenBioCure-Ingestion"
  log_level: "DEBUG"

database:
  host: "${DB_HOST}"
  port: 5432
  database: "${DB_NAME}"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  dialect: "postgresql"
  driver: "asyncpg"
  pool_size: 5
  max_overflow: 10
  schema: "public"

storage:
  type: "azure" # Options: s3, nfs, azure
  azure:
    account_name: ""
    account_key: ""
    container_name: "OpenBioCure-datalake"
    prefix: "documents/"
  s3:
    bucket: "OpenBioCure-datalake"
    prefix: "documents/"
    region: "us-east-1"
    access_key: "" # Leave empty to use IAM role or environment variables
    secret_key: ""
  nfs:
    mount_point: "/mnt/data"
    path: "documents/"

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  vhost: "/"
  exchange: "OpenBioCure"
  queue_prefix: "obc_ingestion_"
  routing_key_prefix: "OpenBioCure.ingestion."
  retry:
    max_attempts: 5
    initial_interval: 1.0 # seconds
    max_interval: 60.0 # seconds
    multiplier: 2.0

grobid:
  host: "localhost"
