name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov pytest-asyncio black isort flake8 mypy

    - name: Lint with flake8
      run: |
        flake8 obc_connector_sdk obc_ingestion connectors tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 obc_connector_sdk obc_ingestion connectors tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check code formatting with black
      run: |
        black --check obc_connector_sdk obc_ingestion connectors tests

    - name: Check import sorting with isort
      run: |
        isort --check-only obc_connector_sdk obc_ingestion connectors tests

    - name: Type check with mypy
      run: |
        mypy obc_connector_sdk obc_ingestion --ignore-missing-imports

    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v --cov=obc_connector_sdk --cov-report=xml --cov-report=term-missing

    - name: Run integration tests
      run: |
        python -m pytest tests/integration/ -v --cov=obc_connector_sdk --cov-report=xml --cov-report=term-missing

    - name: Run connector tests (no network)
      run: |
        python -m pytest tests/connectors/ -v -m "not network" --cov=obc_connector_sdk --cov-report=xml --cov-report=term-missing

    - name: Run smoke tests
      run: |
        python -m pytest tests/ -v -m smoke --cov=obc_connector_sdk --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  connector-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio

    - name: Run connector tests with network
      run: |
        python -m pytest tests/connectors/ -v -m network --timeout=300

    - name: Test PubMed connector
      run: |
        python -m pytest tests/connectors/test_pubmed_connector.py -v -m network --timeout=300

  regression-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio

    - name: Run regression tests
      run: |
        python -m pytest tests/ -v -m regression --timeout=600

    - name: Test all connectors
      run: |
        python tests/test_runner.py --type connectors --network
